import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

import {Roboto} from "next/font/google"
import Navbar from "./_components/Navbar/Navbar";
import { Toaster } from "react-hot-toast";





const roboto = Roboto({
  weight: ["400", "500" ,"100" ,"700"],
  subsets: ["latin"],
  variable:"--Roboto"
})





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${roboto.variable} font-sans antialiased`}
      >
        <Toaster/>
        <ClerkProvider afterSignOutUrl="/sign-in" >
          <Navbar  />
        {children}

        </ClerkProvider>
      </body>
    </html>
  );
}
