import type { Metadata } from "next";
import "../globals.css";

import {ClerkProvider} from "@clerk/nextjs"
import Navbar from "../_components/Navbar/Navbar";
import ToasterProvider from "@/lib/ToasterProvider";
import {Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400","100","300","500","700","900"],
variable:"--Roboto"
})

export const metadata: Metadata = {
  title: "Sabaia Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
        
    <html lang="en">
    <body className={` ${roboto.variable} font-sans antialiased`}>

        <ToasterProvider />
<div className="flex max-lg:flex-col  "   >

{/* Navbar */}

<div className="">
<Navbar />

</div>


        {/*children  */}
       <div className="flex-1" >
        {children}
       </div>
</div>
      </body>
    </html> 
    </ClerkProvider>
 
  );
}
